email_address: abcd@abc.edu # YOUR (uploader's) email address. Used to track submission's ownership
visual_description: High quality images of human faces  # What kind of images does your model generate?
project_description: Nvidia's StyleGAN2 model trained on the Flickr-Faces-HQ Dataset  # Briefly describe how you produced the results
family_name: StyleGAN2  # What architecture the model is based on
project_link: https://github.com/NVlabs/stylegan2  # Link to YOUR page if you fine-tuned the model, otherwise the paper's GitHub repo, HuggingFace page, or website.
download_link: https://drive.google.com/drive/folders/1QHc-yF5C3DChRwSdZKcx1w6K8JvSxQi7  # Link to where you can download the model
paper: https://arxiv.org/abs/1912.04958 # Link to the paper
creator: [person a, person b] # If the model has been fine-tuned by someone other than the authors, fill in its creator's name(s).
bibtex: '@article{DBLP:journals/corr/abs-1912-04958,
  author    = {Tero Karras and
               Samuli Laine and
               Miika Aittala and
               Janne Hellsten and
               Jaakko Lehtinen and
               Timo Aila},
  title     = {Analyzing and Improving the Image Quality of StyleGAN},
  journal   = {CoRR},
  volume    = {abs/1912.04958},
  year      = {2019},
  url       = {http://arxiv.org/abs/1912.04958},
  eprinttype = {arXiv},
  eprint    = {1912.04958},
  timestamp = {Thu, 02 Jan 2020 18:08:18 +0100},
  biburl    = {https://dblp.org/rec/journals/corr/abs-1912-04958.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}' # bibtex for the original paper
display_name: Nvidia StyleGAN2 FFHQ Model # A user-friendly name for your model. This is the name shown to visitors.
resolutions: [512] # The output resolution(s) of your model.
